version: "3.9"

services:
  backend:
    build:
      image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:latest
    container_name: expense-backend
    ports:
      - "5000:3000"
    volumes:
      - ./backend/database.db:/app/database.db
    restart: always

  frontend:
    build:
     image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:latest
    container_name: expense-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always