version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: expense-backend
    ports:
      - "5000:3000"
    volumes:
      - ./backend/database.db:/app/database.db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: expense-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always